### ISSUE TITLE
Use DVML in Razor page

### ISSUE THREAD

**Issue by maggimats** [dynamic-vml/dvml#3]
Hi,

I'm trying to use your library in an existing Razor page but I'm facing issues trying to use it as described in the different sample apps.
Is it technically possible ? I planned to use the controller only to provide the add item action as my data are not coming from an mvc controller but from my Razor page attached model.

Here's the exception I'm having : 

```
System.ApplicationException: Could not find a ViewDataObject for the container OhedgDjyTUqV3wOn4pItCA. Please make sure to call the ListEditorFor method when attempting to show an editor for an IDynamicList.
   at DynamicVML.Extensions.ViewDataExtensions.GetListEditorParameters(ViewDataDictionary viewData, String containerId)
   at DynamicVML.Extensions.EditorExtensions.RenderDynamicListEditor[TModel](IHtmlHelper`1 html)
   at AspNetCore.Areas_Identity_Pages_Shared_EditorTemplates_CustomListTemplateWithFancyButton.ExecuteAsync() in C:\Dev\VS2019\Project\Web\Areas\Identity\Pages\Shared\EditorTemplates\CustomListTemplateWithFancyButton.cshtml:line 16
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TemplateRenderer.Render()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.TemplateBuilder.Build()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.GenerateEditor(ModelExplorer modelExplorer, String htmlFieldName, String templateName, Object additionalViewData)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper`1.EditorFor[TResult](Expression`1 expression, String templateName, String htmlFieldName, Object additionalViewData)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperEditorExtensions.EditorFor[TModel,TResult](IHtmlHelper`1 htmlHelper, Expression`1 expression, String templateName)
   at DynamicVML.Extensions.EditorExtensions.ListEditorFor[TModel,TValue](IHtmlHelper`1 html, Expression`1 propertyExpression, String actionUrl, String addNewItemText, String itemTemplate, String itemContainerTemplate, String listTemplate, String listContainerTemplate, Object additionalViewData, ListRenderMode mode, NewItemMethod method)
Exception levée : 'DynamicVML.DynamicListException' dans DynamicVML.dll
Error rendering list container template 'CustomListTemplateWithFancyButton' when calling ListEditorFor. Check the inner exception and other properties of this exception for details. Message: Could not find a ViewDataObject for the container OhedgDjyTUqV3wOn4pItCA. Please make sure to call the ListEditorFor method when attempting to show an editor for an IDynamicList.
```

Thanks for your help

**Comment by cesarsouza** [comment]
Salut @maggimats,

Hmmm that's a good question. I've never attempted to use the library with a standalone razor page. Can you share a .zip containing a minimum example of an application using a razor page + DVML so I can try to make it work and update the library if necessary?

**Comment by hmncube** [comment]
Nay news here?

**Comment by cesarsouza** [comment]
Hi @hmncube,

Yes, the current version here in repository should now work with Razor pages. I am not sure if the latest release on NuGet has been updated since I added this here though... Did you give it a try? If yes and you got an error, could you please let me know which error it was?

Regards,
Cesar

**Comment by cesarsouza** [comment]
I've just made a new release that should work with Razor Pages: https://github.com/dynamic-vml/dvml/releases/tag/v1.4.0

It is also available in NuGet: https://www.nuget.org/packages/DynamicVML/

To use the library from within a razor page, just call the @Html.ListEditorFor or @Html.DisplayListFor methods from within the .cshtml as usual. In respect to the implementation of the action method that creates the new item, I would recommend using a separate controller just to provide the AddNewItem methods as shown in the sample applications. While it should be possible to write those methods in the PageModel directly, it can be somewhat tricky.
